spring:
  datasource:
    url: jdbc:mysql://172.16.6.31:3306/test
    username: root
    password: 123456
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: debug
    org:
      springframwwork: debug
      org:
        mybatis: debug

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xiaoh.springboot.transaction.domain